### ISSUE TITLE
fetching submodule vinecopulib fails with "fatal: reference is not a tree"

### ISSUE THREAD

**Issue by migueldiascosta** [vinecopulib/pyvinecopulib#115]
Looks like the commit being linked to, https://github.com/vinecopulib/vinecopulib/tree/da0668289889b28be899ba7510bf94a97ebbfabc, was not pushed to that repo, link to https://github.com/vinecopulib/vinecopulib/tree/258eb2d7758ce067ee7d53789067f0d3ebbb9375 instead?

**Comment by tvatter** [comment]
Hi, sorry, but I'm not sure how to reproduce this issue. When I run `git clone --recursive https://github.com/vinecopulib/pyvinecopulib.git`, it works seamlessly.

**Comment by migueldiascosta** [comment]
@tvatter it's possible that the `fatal: reference is not a tree` error only occurs with old versions of git, I can still reproduce it on version 1.8.3.1 (which is pretty old, sure) but you're right, it doesn't fail on e.g. 2.38.1

**Comment by tvatter** [comment]
While it shouldn't change anything as the offending commit as simply be bundled and merged as part of the latest release, I've pulled the correct/new `vinecopulib` commit in the [`dev` branch of `pyvinecopulib`](https://github.com/vinecopulib/pyvinecopulib/tree/dev).

I'm going to close as using the `dev` branch should solve the issue while waiting for the release to `main`, but feel free to reopen otherwise.
