### ISSUE TITLE
I want to change the parameter object of Vinecop, what should I do?

### ISSUE THREAD

**Issue by YwhAqy99** [vinecopulib/pyvinecopulib#129]
![微信截图_20240330213746](https://github.com/vinecopulib/pyvinecopulib/assets/165484620/ab6e0856-398e-4717-9fe7-97d19c992c0d)
Direct assignment does not report an error but it is not feasible. Is there a way to modify parameters in the methods of this object

**Comment by tvatter** [comment]
Hi,

Apologies for the late answer.

Something weird is happening indeed and I need to investigate. In the meantime, here's something that works:

```
import pyvinecopulib as pv
import numpy as np

cop = pv.Bicop(family=pv.BicopFamily.gaussian) ## parameter is [[0]]

cop.parameters = np.array([[0.5]]) ## parameters is now [[0.5]])
```

What puzzles me is that it does indeed not seem to work when assigning using `cop.parameters[0][0] = something`.

**Comment by tvatter** [comment]
Alright, after investigation, here's what's going on.  The issue you're encountering stems from the fact that the C++ getter method is returning a copy of the underlying data rather than a reference to it. When you access it in Python, it creates a new numpy array, but any changes you make to this numpy array won't be reflected back in the original data on the C++ side.

The method that I suggested actually ensures one is using the C++ setter method, which prevents the user from shooting him/her-self in the foot by checking that the parameters are valid. For instance, with the Gaussian copula, you need an np array of shape `(1, 1)` that contains a float between -1 and 1, for the Student, there is the degree of Freedom that needs to be >2, etc...

As a result, I've removed the bug label, because it's actually a feature. I'm going to close for now as the intended way to modify a parameter is through the setter, and which works as intended. But feel free to reopen if this is still an issue for you or if you have a suggestion/need.
