### ISSUE TITLE
Plot Function like in R

### ISSUE THREAD

**Issue by TY-Cheng** [vinecopulib/pyvinecopulib#75]
Thank you so much for this masterpiece package.

Just wondering if we have plot function implemented for pyvinecopulib? just like rvinecopulib in R?
The exported json file is not yet directly compatible with 'igraph' or 'networkx', it would be more helpful to customised visualisation if they are compatible. thx a lot!

**Comment by tvatter** [comment]
Hi and thanks for your kind words!

There are questions within this issue:

* Regarding having a plot function in `pyvinecopulib`: the thing is, both `rvinecopulib` and `pyvinecopulib` are wrappers around `vinecopulib`, a C++ library for vine copulas modeling, but they differ completely in their design/implementation. Because R users are less used to object-oriented code, we needed to write wrappers that would look/feel familiar to the typical user. But Python is much closer to C++ in the sense that people are used to work with classes/methods. As a result, `pyvinecopulib` simply exposes the C++ classes and their methods using pybind11. Actually, `pyvinecopulib` is almost entirely contained in [this C++ file](https://github.com/vinecopulib/pyvinecopulib/blob/master/src/main.cpp), and we haven't written much actual Python code. We would need to look at existing stuff for plotting in Python, but we simply haven't taken the time to do it yet. Any help on that would be welcome :)
* Regarding the exported json file: actually, the file contains far more than just the structure of the vine, as one needs also the bivariate copula families and their parameters. However, I am guessing that standard network libraries have functions to read from an edge list or adjacency matrix? We could have a method allowing to export the structure as a list of trees, each encoded as an edge list or adjacency matrix. But remember, the structure is not a single graph, it's really a list of graphs. An alternative would be to have a method allowing to export a given tree as an edge list or adjacency matrix. @tnagler any thoughts?

**Comment by tnagler** [comment]
Having some extra visualization functionality in Python would generally be a good idea, but I think both @tvatter and I don't have much time for this at the moment. 

Converting the vine into adjacency matrices or similar would be easy to implement in the meanwhile, but would still require a lot of extra work from the user. Could you build something from there and maybe contribute it to our library, @TY-Cheng? :)

**Comment by tvatter** [comment]
Plot functions have been added to the [dev branch](https://github.com/vinecopulib/pyvinecopulib/tree/dev) in #143. For technical details, plotting routines have been implemented in pure Python and bound to the C++ objects so that for bivariate and vine copulas now expose a `plot()` method. I'm closing the issue but feel free to reopen if needed.
