### ISSUE TITLE
Cross-compiling issues with google colab

### ISSUE THREAD

**Issue by tvatter** [vinecopulib/pyvinecopulib#87]
When trying to install the binaries on google colab via `!pip install pyvinecopulib`, then doing `import pyvinecopulib` leads to `/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found`.

The error is similar to [this](https://github.com/jblindsay/whitebox-tools/issues/112) and seems like a cross-compiling issue. A temporary solution to just "make it work" is to install from source via `!pip install git+https://github.com/vinecopulib/pyvinecopulib`, but we should obviously fix this properly.

**Comment by slayoo** [comment]
@tvatter It should be enough to compile the packages with a manylinux-compatible setup. So, instead of this:
https://github.com/vinecopulib/pyvinecopulib/blob/2483b695697ba8138d1c08364a8f05bd9c104487/.github/workflows/pypi.yml#L108
we can run the build using:
https://github.com/RalfG/python-wheels-manylinux-build

**Comment by tvatter** [comment]
Version 0.6.5 is now available on PyPi and the binaries are now properly portable using [cibuildwheels](https://github.com/pypa/cibuildwheel). It should work "as is" on most Linux, macos, and windows computers. I've tested on a few systems and it seems to work, so I'm going to close for now, but feel free to reopen otherwise.
